# Generated by Django 3.0.2 on 2020-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g05', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdate', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Paymentid',
        ),
    ]
