# Generated by Django 3.0.2 on 2020-01-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g05', '0002_auto_20200102_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
